# Generated by Django 2.2.7 on 2020-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('idescription', models.CharField(blank=True, max_length=500, null=True)),
                ('itime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=40, null=True)),
                ('pdescription', models.CharField(blank=True, max_length=500, null=True)),
                ('ptime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=40, null=True)),
                ('sdescription', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('uname', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('disname', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
